### PR TITLE
Add gsoc hyperpars intro blog post

### PR DESCRIPTION
**Pull request by masongallo**
- [x] Add blog post draft
- [x] Confirm blog post displays properly
- [ ] Push the big green button

### CODE REVIEW

**Comment by masongallo** [comment]
Based on feedback from @larskotthoff, I revised the blog post.

A draft is available here: http://masongallo.github.io/machine/learning,/r/2016/08/24/gsoc-hyperparameter-tuning-visualization.html 

@berndbischl ?

**Comment by larskotthoff** [comment]
The link you've posted doesn't work, but it reads great! I think that this is a big improvement over the previous draft, thanks!

**Comment by larskotthoff** [comment]
@MasonGallo If this is done, could you please retag/change the title appropriately?

**Comment by masongallo** [comment]
Sorry! Here's the fixed URL: http://masongallo.github.io/machine/learning/r/2016/08/24/gsoc-hyperparameter-tuning-visualization.html

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
